### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ghost** [Muqsit/PMArmorStand#1]
`Error: Call to undefined method pocketmine\nbt\tag\CompoundTag::hasTag()
File: plugins/PMArmorStand_dev-5.phar/src/muqsit/pmarmorstand/entity/ArmorStandEntity
Line: 114
Type: Error`

`Backtrace:
#0 pmsrc/src/entity/Entity(245): muqsit\pmarmorstand\entity\ArmorStandEntity->initEntity(object pocketmine\nbt\tag\CompoundTag)
#1 plugins/PMArmorStand_dev-5.phar/src/muqsit/pmarmorstand/ArmorStandItem(32): pocketmine\entity\Entity->__construct(object pocketmine\entity\Location)
#2 pmsrc/src/world/World(1752): muqsit\pmarmorstand\ArmorStandItem->onInteractBlock(object pocketmine\player\Player, object pocketmine\block\Air, object pocketmine\block\Grass, integer 1, object pocketmine\math\Vector3)
#3 pmsrc/src/player/Player(1622): pocketmine\world\World->useItemOn(object pocketmine\math\Vector3, object muqsit\pmarmorstand\ArmorStandItem, integer 1, object pocketmine\math\Vector3, object pocketmine\player\Player, boolean 1)
#4 pmsrc/src/network/mcpe/handler/InGamePacketHandler(369): pocketmine\player\Player->interactBlock(object pocketmine\math\Vector3, integer 1, object pocketmine\math\Vector3)
#5 pmsrc/src/network/mcpe/handler/InGamePacketHandler(230): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemTransaction(object pocketmine\network\mcpe\protocol\types\inventory\UseItemTransactionData)
#6 pmsrc/src/network/mcpe/protocol/InventoryTransactionPacket(106): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
#7 pmsrc/src/network/mcpe/NetworkSession(398): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler)
#8 pmsrc/src/network/mcpe/NetworkSession(361): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket, string[56] .......A......@.................VCr=.B'.MC.^W?...?..x?. )
#9 pmsrc/src/network/mcpe/raklib/RakLibInterface(186): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[57] c.abd.b.9.&..5.....X.p80.....l]..\d.......!........l.....)
#10 pmsrc/vendor/pocketmine/raklib/src/server/ipc/RakLibToUserThreadMessageReceiver(43): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[66] .....hs................13 .z-j.d...?.....zi..=.3.D......C.Q..1L.*.)
#11 pmsrc/src/network/mcpe/raklib/RakLibInterface(121): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface)
#12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
#14 pmsrc/src/Server(1593): pocketmine\snooze\SleeperHandler->sleepUntil(double 1618990610.3449)
#15 pmsrc/src/Server(1143): pocketmine\Server->tickProcessor()
#16 pmsrc/src/PocketMine(276): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[39] /root/grytic/pmmp/PocketMine-MP/server/, string[47] /root/grytic/pmmp/PocketMine-MP/server/plugins/)
#17 pmsrc/src/PocketMine(299): pocketmine\server()
#18 pmsrc(11): require(string[83] phar:///root/grytic/pmmp/PocketMine-MP/server/PocketMine-MP.phar/src/PocketMine.)`

**Comment by Muqsit** [comment]
b036c9a062a6c56dec38f944fd6f79a822ad5179
