### ISSUE TITLE
ArmorStand get destroyed in Plot worlds

### ISSUE THREAD

**Issue by MrBlasyMSK** [Muqsit/PMArmorStand#3]
The armor rstand can be broken by ot her players whit the hand in the world of plots. You can also break it with the bow

**Comment by Muqsit** [comment]
That's something a plot plugin must work towards ensuring doesn't happen.

**Comment by MrBlasyMSK** [comment]
https://poggit.pmmp.io/p/ArmorStandExpanded/1.2.10


[What about the PlotProtection?](https://poggit.pmmp.io/p/ArmorStandExpanded/1.2.10#rdesc-section-what-about-the-plotprotection)

Since the ArmorStand is usually not implemented in Pocketmine-MP, it is not checked by the MyPlot PlotProtection.

ArmorStandExpanded does this for you.

You can include it too, but I understand that you might be lazy on that

**Comment by Muqsit** [comment]
> https://poggit.pmmp.io/p/ArmorStandExpanded/1.2.10
> 
> [What about the PlotProtection?](https://poggit.pmmp.io/p/ArmorStandExpanded/1.2.10#rdesc-section-what-about-the-plotprotection)
> 
> Since the ArmorStand is usually not implemented in Pocketmine-MP, it is not checked by the MyPlot PlotProtection.
> 
> ArmorStandExpanded does this for you.
> 
> You can include it too, but I understand that you might be lazy on that

It's not about laziness, it just doesn't seem right to include MyPlot / PlotProtection code in this plugin. This is just a barebones implementation of armor stands.
It makes more sense for protection plugins to ensure stuff like this doesn't happen.

**Comment by MrBlasyMSK** [comment]
Yes and I give you all the reason, but in his part he has created a plugin for plots and with protection of objects that have Pocketmine, this being a plugin, is not implemented and I doubt that he wants to add the object to the protection system.
In any case it would be great if you make a PR to add your ArmorStand to the protection list.
And if that does not work the thing would be to add your protection in your case.
(this is just a recommendation, since the last ArmorStand plugin had it by default).
